### ISSUE TITLE
import daal4py fails on MacOSX

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/daal4py#152]
Create an environment `b_d4py` with Python 3.7.6 needed to build daal4py:

```text
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/bzip2-1.0.8-h01d97ff_1.tar.bz2
https://conda.anaconda.org/intel/osx-64/daal-include-2020.0-intel_166.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2019.11.28-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-9.0.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/llvm-openmp-9.0.0-h40edb58_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mpi-1.0-mpich.tar.bz2
https://conda.anaconda.org/intel/osx-64/tbb-2020.0-intel_166.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.4-h1de35cc_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h0b31af3_1006.tar.bz2
https://conda.anaconda.org/intel/osx-64/daal-2020.0-intel_166.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-h6de7cb9_1006.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-4.0.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libllvm9-9.0.1-ha1b3eb9_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.1-h0a44026_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1d-h0b31af3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tapi-1000.10.8-ha1b3eb9_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.10-hbbe82c9_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/clang-9.0.1-default_hf57f61e_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ld64-450.3-h3c32e8a_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libopenblas-0.3.7-h4bb4525_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mpich-3.3.2-hc856adb_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.0-hcfe32e1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cctools-927.0.2-h5ba7a2e_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/clangxx-9.0.1-default_hf57f61e_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.8.0-14_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.30.1-h93121df_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/compiler-rt_osx-64-9.0.1-h6a512c6_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.8.0-14_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.8.0-14_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.7.6-h5c2c468_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2019.11.28-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/compiler-rt-9.0.1-h6a512c6_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cython-0.29.14-py37h4a8c4bd_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/markupsafe-1.1.1-py37h0b31af3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/numpy-1.17.3-py37hde6bac1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/clang_osx-64-9.0.1-h05bbb7f_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-41.6.0-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/clangxx_osx-64-9.0.1-h05bbb7f_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.10.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/wheel-0.33.6-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pip-19.3.1-py37_0.tar.bz2
```

Activate the environment, and build the latest source of daal4py (29582659027c3efa6482aa61d108a5daddbb56a3) as follows:

```bash
LDFLAGS="${LDFLAGS//-Wl,-dead_strip_dylibs}" \
 LDFLAGS_LD="${LDFLAGS_LD//-dead_strip_dylibs}" \
 LDSHARED="-bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names" \  
 DAAL4PY_VERSION=2020 \
 TBBROOT=$CONDA_PREFIX \
 MPIROOT=$CONDA_PREFIX \
 DAALROOT=$CONDA_PREFIX \
 python setup.py build_ext --inplace
```

It builds without errors. However, running "python -c 'import _daal4py'" fails:

```
(b_d4p) [14:02:40 mymac daal4py]$ python -c 'import _daal4py; print(_daal4py.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit__daal4py)
```

Indeed, the native extension does not seem to have the symbol, as checked with ``nm -A _daal4py.cpython-37m-darwin.so | grep PyInit``.

Downgrading Python from 3.7.6 to 3.7.3 with `conda install -c conda-forge python=3.7.3`,  and repeating build steps gives a working extension:

```
(b_d4p) [14:09:12 mymac daal4py]$ python -c 'import _daal4py; print(_daal4py.__version__)'
(2020, 0)
```

This is reminiscent of https://github.com/numpy/numpy/issues/13822

Reproduced in:

```
      System Version: OS X 10.11.4 (15E65)
      Kernel Version: Darwin 15.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

**Comment by oleksandr-pavlyk** [comment]
I have verified that Cythonized files `build/daal4py_cy.cpp` produced between two scenarios are identical. 

The `PyInit__daal4py` routine generated is quite small to be quoted directly:

```c
#if PY_MAJOR_VERSION < 3
__Pyx_PyMODINIT_FUNC init_daal4py(void) CYTHON_SMALL_CODE; /*proto*/
__Pyx_PyMODINIT_FUNC init_daal4py(void)
#else
__Pyx_PyMODINIT_FUNC PyInit__daal4py(void) CYTHON_SMALL_CODE; /*proto*/
__Pyx_PyMODINIT_FUNC PyInit__daal4py(void)
#if CYTHON_PEP489_MULTI_PHASE_INIT
{
  return PyModuleDef_Init(&__pyx_moduledef);
}
```

**Comment by oleksandr-pavlyk** [comment]
Here is a small reproducer. In the environment with Python 3.7.6, create the following toy extension, with file `primes.pyx`:

```python

# distutils: language = c++
#cython: language_level=2

def primes(int nb_primes):
    cdef int n, i, len_p
    cdef int p[1000]
    if nb_primes > 1000:
        nb_primes = 1000

    len_p = 0  # The current number of elements in p.
    n = 2
    while len_p < nb_primes:
        # Is n prime?
        for i in p[:len_p]:
            if n % i == 0:
                break

        # If no break occurred in the loop, we have a prime.
        else:
            p[len_p] = n
            len_p += 1
        n += 1

    # Let's return the result in a python list:
    result_as_list  = [prime for prime in p[:len_p]]
    return result_as_list
```

and `setup.py`:

```python
from setuptools import setup, Extension
from Cython.Build import cythonize

eca = ['-fstack-protector', '-fPIC',
       '-D_FORTIFY_SOURCE=2', '-Wformat', '-Wformat-security',]
eca += ['-stdlib=libc++', '-w']

setup(
    ext_modules=cythonize(
        [Extension(
            'primes',
            ['primes.pyx'],
            language='cpp',
            extra_compile_args=eca,
            )])
)
```

Now, compiling in place

```sh
git clean -dfx && python setup.py build_ext --inplace
```

the extension works as expected:

```sh
(b_d4p6) [14:52:22 mymac a]$ python -c "import primes; print(primes.primes(10))"
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
```

But should I set those env. variables, like in the original example, it starts failing. 

```sh
git clean -dfx
LDFLAGS="${LDFLAGS//-Wl,-dead_strip_dylibs}" LDFLAGS_LD="${LDFLAGS_LD//-dead_strip_dylibs}" LDSHARED="-bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names" 
python setup.py build_ext --inplace
```

```sh
(b_d4p6) [14:54:58 mymac a]$ python -c "import primes; print(primes.primes(10))"                                                   Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_primes)
```

**Comment by oleksandr-pavlyk** [comment]
The reproducer gets fixed if `LDSHARED` is augmented with `-Wl,-export_dynamic`.

I can confirm that this resolve the issue with daal4py as well.

**Comment by oleksandr-pavlyk** [comment]
For my own sake mostly, more background on [what `-export_dynamic` does](https://stackoverflow.com/questions/36692315/what-exactly-does-rdynamic-do-and-when-exactly-is-it-needed).

**Comment by oleksandr-pavlyk** [comment]
Archiving what @jjhelmus said on conda-forge gitter:

> My guess is that this a result of python/cpython#12348, prior to Python 3.7.4 extensions are build with sysconfig["OPT"] + environ["CFLAGS"] in 3.7.4 and newer this becomes sysconfig["CFLAGS"] + environ["CFLAGS"]. Also see https://bugs.python.org/issue36235 

> The sysconfig CFLAGS includes -flto and -Wl,-export_dynamic which are not in OPT, one of those might be causing the symbol to be suppressed

**Comment by oleksandr-pavlyk** [comment]
Since #151 has been merged, resolving.
